#ifndef LIBXLSREAD_GLOBAL_H
#define LIBXLSREAD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBXLSREAD_LIBRARY)
#  define LIBXLSREADSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBXLSREADSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBXLSREAD_GLOBAL_H
