#ifndef LIBXLSWRITE_GLOBAL_H
#define LIBXLSWRITE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBXLSWRITE_LIBRARY)
#  define LIBXLSWRITESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBXLSWRITESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBXLSWRITE_GLOBAL_H
